services:
  php-fpm:
    build: .
    container_name: php-fpm
    env_file:
      - .env
    volumes:
      - ./app:/app # Mount the Symfony app correctly
      - vendor:/app/vendor
    networks:
      - yessirski
    depends_on:
      - mariadb
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - yessirski
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./app:/app # Ensure Caddy sees the Symfony project
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - php-fpm
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    env_file: .env
    networks:
      - yessirski
    volumes:
      - mysql_data:/var/lib/mysql
networks:
  yessirski:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
  mysql_data:
  vendor:
